[WIP][checkpoint][dt] Add SavePlanner for Distributed Tensor
pytorch/tau pull request #462
Opened 2022-09-15 17:18 UTC by wz337

WIP
Add SavePlanner support for both Sharded Distributed Tensor and Replicated Distributed Tensor.

2022-09-15 19:00 UTC, kumpera requested changes

2022-09-15 20:13 UTC, kumpera commented on spmd/dt_save_planner.py
> +                self.dedup_replicated_tensors = dedup_replicated_tensors
What happens if the second tensor is sharded?

2022-09-15 20:36 UTC, kumpera commented on spmd/dt_save_planner.py
> +            if isinstance(obj, DTensor):
This needs an else clause to handle non-dt stuff.

2022-09-15 20:45 UTC, wz337 commented on spmd/dt_save_planner.py
> +            if isinstance(obj, DTensor):
This doesn't handle non-DT write items.
Add else.

2022-09-26 17:13 UTC, kumpera approved these changes
LGTM.
Fixing the test directory should be done as it will lead to unreliable tests otherwise.

2022-09-26 17:13 UTC, kumpera commented on spmd/checkpoint/dt_planner.py
> +        self.dedup_replicated_tensors: bool = dedup_replicated_tensors
should call ``super(DistributedTensorSavePlanner).__init__()``

2022-09-26 17:13 UTC, kumpera commented on test/spmd/checkpoint/test_dt_planner.py
> +CHECKPOINT_DIR = "/scratch/checkpoint/test_dt_planner/"
For a test suite we should use a temporary generated name. For example: https://github.com/pytorch/pytorch/pull/84952

2022-09-26 23:50 UTC, kumpera approved these changes

2022-09-27 23:03 UTC, closed without merging